### ISSUE TITLE
Multi instance monitoring

### ISSUE THREAD

**Issue by smycek** [xperimental/nextcloud-exporter#41] opened 2021-04-01 20:15 UTC
Do you have some recommendations or best practice when setting up monitoring multiple Nextcloud Instances?

**Comment by xperimental** [comment] 2021-04-12 19:07
I personally have no experience with monitoring a large Nextcloud installation, because I only host relatively small ones. 

Exporters usually have a 1:1 relationship with the service they are monitoring. In this case this could be interpreted as one of the following:

- one exporter instancer per server hosting the Nextcloud instance
- one exporter per "logical Nextcloud instance"

I'm leaning towards the second one, because the exporter mostly monitors metrics of the Nextcloud installation and not the underlying server, for which there should be other exporters available already.

**Comment by rtt-mmk** [comment] 2021-05-12 18:56
We run a nextcloud installation of 10 Nextcloud-Apache-Hosts in front of DB- and Redis-Cluster.

For the monitoring we habe an addition host fully equipped with nextcloud. On this node we query the serverinfo.php to write the output into our time-series-database. Detailed metrics (OS, Filesystems etc.) of the servers we collect with an extra server-agent on all servers. I can confirm, that querying the nextcloud endpoint only from one server is suitable in larger setups, too.

**Comment by hoamer** [comment] 2021-06-09 08:14
Hi,

I just want to share my setup, with "multi" (3 instances). 
For example, config files are thrown in "/etc/prometheus_nextcloud_exporter/". 

Then I created this unitfile, which is suitable for multiple instance of the nc-exporter: /etc/systemd/system/prometheus_nextcloud_exporter@.service
```
[Unit]
Description=%i service for prometheus exporter for nextcloud
Requires=nginx.service
After=nginx.service

[Service]
Type=simple
RemainAfterExit=true
ExecStart=prometheus_nextcloud_exporter -c /etc/prometheus_nextcloud_exporter/%i.yml

[Install]
WantedBy=multi-user.target
```

where 
```
systemctl start prometheus_nextcloud_exporter@nextcloud_instance_1
```

i.e. is 
```
/etc/prometheus_nextcloud_exporter/nextcloud_instance_1.yml
```

**Comment by xperimental** [comment] 2021-08-16 19:09
@hoamer The service unit in the `contrib/` folder sets some additional parameters to improve security, but it can also be easily updated for instancing like you did.

@smycek Has any of the existing posts answered your questions? Would it be okay to close the issue?

**Comment by jhjacobs81** [comment] 2021-11-23 11:44
this is actually just what i ws looking for! awesome!

**Comment by rtt-mmk** [comment] 2021-11-30 20:31
Just for info: To cope with the scaling issues while counting files-statistics in large installation nextcloud tranferred theses queries to a long-running background cronjob (since Version 21.0.2 - https://github.com/nextcloud/serverinfo/pull/298).

**Comment by smycek** [comment] 2021-12-01 18:28
> @smycek Has any of the existing posts answered your questions? Would it be okay to close the issue?

My question has been answered, I am fine if you close the issue. Thanks to everybody!

**Comment by xperimental** [comment] 2021-12-04 15:37
Great. Thanks for the input, everyone.

**Closed by xperimental** 2021-12-04 15:37 UTC
Labels: question
