### ISSUE TITLE
Debug Output?

### ISSUE THREAD

**Issue by PySualk** [xperimental/nextcloud-exporter#4] opened 2018-12-14 09:20 UTC
```bash
2018/12/14 09:13:07 Nextcloud server: xxxUser: xxx
2018/12/14 09:13:07 Listen on :9205...
2018/12/14 09:14:26 Error during scrape: XML syntax error on line 43: attribute name without = in element
2018/12/14 09:14:27 Error during scrape: XML syntax error on line 43: attribute name without = in element
2018/12/14 09:14:45 Error during scrape: XML syntax error on line 43: attribute name without = in element
```

I encountered a problem while scraping my Nextcloud instance. Is there a way to get some sort of debug output to isolate the problem?

**Comment by xperimental** [comment] 2018-12-15 14:32
Currently there is no possibility to enable further debug output in nextcloud-exporter.

But the error message already gives an indication of what the issue is: a syntax error in the XML file the exporter uses to get the data.

You could try downloading the XML file that the exporter uses yourself and check what it contains in line 43, or post it here if it does not contain any sensitive information.

**Comment by xperimental** [comment] 2019-01-05 13:20
@PySualk Did you find the issue in the XML?

**Comment by xperimental** [comment] 2019-01-08 21:01
@ochorocho From your comment it looks like you do not run the exporter with the correct "info URL". I had already noticed that I had no information about this in the README and assumed that this was also the case for @PySualk, but did not get to changing it until now.

I have just added a [small paragraph about the URL in the README](https://github.com/xperimental/nextcloud-exporter#info-url). Could you check if that is of any use for you?

If the exporter still does not work when you give it the correct server info URL, I'd be happy if you could post the XML content here, maybe with a bit of anonymization applied to it.

**Comment by ochorocho** [comment] 2019-01-08 22:11
@xperimental thanks now it works perfectly. :-)

Now running this command does the job:
```
/root/go/bin/nextcloud-exporter -p PASSWORD -u NEXTCLOUD_USER -l https://cloud.domain.org//ocs/v2.php/apps/serverinfo/api/v1/info
```

**Comment by xperimental** [comment] 2019-01-11 14:40
Great. I hope this has also fixed the issue for @PySualk.
I am closing this now, please comment if there are still issues.

**Closed by xperimental** 2019-01-11 14:40 UTC
